
Cuando se produce un error de RunTime(Tiempo de ejecuci√≥n) se produce una
"Exception", para capturar esto, hacemos uso de "try" y "catch" y opcionalmente "finally"


